### ISSUE TITLE
Known bugs 

### ISSUE THREAD

**Issue by Jillium** [maxh1231/no1fan#80]
- Artist name on random track is a link that doesn't go anywhere, the loading bar just spins
- Search page- some artist links do not go anywhere, the loading bar just spins

**Comment by Jillium** [comment]
Do we need dashboard.js?

**Comment by Jillium** [comment]
Setlist.fm api key breaking when too many calls at once

**Comment by maxh1231** [comment]
updated original comment with bugs

**Comment by Thorulfr** [comment]
> Do we need dashboard.js?

JK, we can delete it. I didn't end up using it.

**Comment by Jillium** [comment]
I ended up using it today :)

**Comment by Thenlie** [comment]
* Artist name on random track is a link that doesn't go anywhere, the loading bar just spins
* Search page- some artist links do not go anywhere, the loading bar just spins

Both of these issues have been fixed by adding a "Blank Results" page.
